<?php
namespace Database\Seeders;

use App\Models\CompetitionContentTimeline;
use Illuminate\Database\Seeder;

class CompetitionContentTimelineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $competition_content_timelines = [
            [
                'competition_content_id' => '1',
                'title'                  => 'Coming Soon',
                'end_date'               => '2025-06-30 15:59:59',
                'date_range'             => 'Comming Soon',
                'start_date'             => '2025-06-26 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Pendaftaran Batch 1 dan Pengumpulan BMC & Proposal',
                'end_date'               => '2025-07-20 15:59:59',
                'date_range'             => '1 - 20 Juli 2025',
                'start_date'             => '2025-06-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Pendaftaran Batch 2 dan Pengumpulan BMC & Proposal',
                'end_date'               => '2025-08-20 15:59:59',
                'date_range'             => '21 Juli - 20 Agustus 2025',
                'start_date'             => '2025-07-20 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Perpanjangan Pendaftaran dan Pengumpulan BMC & Proposal',
                'end_date'               => '2025-08-31 15:59:59',
                'date_range'             => '21 - 31 Agustus 2025',
                'start_date'             => '2025-08-20 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-10-02 15:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-10-01 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Pengumpulan Video Iklan Singkat',
                'end_date'               => '2025-10-18 15:59:59',
                'date_range'             => '5 Oktober - 18 Oktober 2025',
                'start_date'             => '2025-10-04 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-10-19 15:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-10-18 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Expo Video Iklan Singkat',
                'end_date'               => '2025-10-29 15:59:59',
                'date_range'             => '22 Oktober - 29 Oktober 2025',
                'start_date'             => '2025-10-21 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Babak Final dan Pengumuman Juara',
                'end_date'               => '2025-10-01 15:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-10-31 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '2',
                'title'                  => 'Coming soon',
                'end_date'               => '2024-08-07 23:59:59',
                'date_range'             => 'Coming soon',
                'start_date'             => '2024-08-01 00:00:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Coming Soon',
                'end_date'               => '2025-06-30 15:59:59',
                'date_range'             => 'Comming Soon',
                'start_date'             => '2025-06-26 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-07-20 15:59:59',
                'date_range'             => '1 Juli – 20 Juli 2025',
                'start_date'             => '2025-06-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-08-20 15:59:59',
                'date_range'             => '22 Juli – 20 Agustus 2025',
                'start_date'             => '2025-07-21 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-08-31 15:59:59',
                'date_range'             => '21 Agustus – 31 Agustus 2025',
                'start_date'             => '2025-08-20 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-10-02 15:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-10-01 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-10-19 15:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-10-18 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Babak Final',
                'end_date'               => '2025-10-31 15:59:59',
                'date_range'             => '31 Oktober 2025',
                'start_date'             => '2025-10-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Pengumuman Juara',
                'end_date'               => '2025-11-01 15:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-10-31 16:00:01',
                'description'            => '',
            ],

            [
                'competition_content_id' => '4',
                'title'                  => 'Coming Soon',
                'end_date'               => '2025-06-30 15:59:59',
                'date_range'             => 'Comming Soon',
                'start_date'             => '2025-06-26 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '4',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-07-20 15:59:59',
                'date_range'             => '1 Juli – 20 Juli 2025',
                'start_date'             => '2025-06-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '4',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-08-20 15:59:59',
                'date_range'             => '22 Juli – 20 Agustus 2025',
                'start_date'             => '2025-07-21 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '4',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-08-31 15:59:59',
                'date_range'             => '21 Agustus – 31 Agustus 2025',
                'start_date'             => '2025-08-20 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '4',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-10-02 15:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-10-01 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '4',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-10-19 15:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-10-18 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '4',
                'title'                  => 'Babak Final dan Pengumuman Juara',
                'end_date'               => '2025-11-01 15:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-10-31 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Coming Soon',
                'end_date'               => '2025-06-30 15:59:59',
                'date_range'             => 'Comming Soon',
                'start_date'             => '2025-06-26 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-07-20 15:59:59',
                'date_range'             => '1-20 Juli 2025',
                'start_date'             => '2025-06-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-08-20 15:59:59',
                'date_range'             => '22 Juli-20 Agustus 2025',
                'start_date'             => '2025-07-21 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-08-31 15:59:59',
                'date_range'             => '21-31 Agustus 2025',
                'start_date'             => '2025-08-20 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Technical Meeting Penysihan',
                'end_date'               => '2025-09-05 15:59:59',
                'date_range'             => '5 September 2025',
                'start_date'             => '2025-09-04 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-10-02 15:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-10-01 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Technical Meeting Final',
                'end_date'               => '2025-10-19 15:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-10-18 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Babak Final dan Pengumuman Juara',
                'end_date'               => '2025-11-01 15:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-10-31 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '6',
                'title'                  => 'Coming soon',
                'end_date'               => '2024-08-07 23:59:59',
                'date_range'             => 'Coming soon',
                'start_date'             => '2024-08-01 00:00:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Coming Soon',
                'end_date'               => '2025-06-30 15:59:59',
                'date_range'             => 'Comming Soon',
                'start_date'             => '2025-06-26 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-07-20 15:59:59',
                'date_range'             => '1-20 Juli 2025',
                'start_date'             => '2025-06-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-08-20 15:59:59',
                'date_range'             => '22 Juli-20 Agustus 2025',
                'start_date'             => '2025-07-21 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-08-31 15:59:59',
                'date_range'             => '21-31 Agustus 2025',
                'start_date'             => '2025-08-20 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-10-19 15:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-10-18 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Babak Penyisihan',
                'end_date'               => '2025-10-31 15:59:59',
                'date_range'             => '31 Oktober 2025',
                'start_date'             => '2025-10-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Babak Semifinal 1, 2, 3, 4 & Pengumuman Juara',
                'end_date'               => '2025-11-01 15:59:59',
                'date_range'             => '31 Oktober - 1 November 2025',
                'start_date'             => '2025-10-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Coming Soon',
                'end_date'               => '2025-06-30 15:59:59',
                'date_range'             => 'Comming Soon',
                'start_date'             => '2025-06-26 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-07-20 15:59:59',
                'date_range'             => '1 Juli - 20 Juli 2025',
                'start_date'             => '2025-06-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-08-20 15:59:59',
                'date_range'             => '22 Juli – 20 Agustus 2025',
                'start_date'             => '2025-07-21 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-08-31 15:59:59',
                'date_range'             => '21 Agustus – 31 Agustus 2025',
                'start_date'             => '2025-08-20 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-10-02 15:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-10-01 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-10-19 15:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-10-18 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Babak Final dan Pengumuman Juara',
                'end_date'               => '2025-11-01 15:59:59',
                'date_range'             => '1 November 2025 ',
                'start_date'             => '2025-10-31 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Coming Soon',
                'end_date'               => '2025-06-30 15:59:59',
                'date_range'             => 'Comming Soon',
                'start_date'             => '2025-06-26 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-07-20 15:59:59',
                'date_range'             => '1 Juli - 20 Juli 2025',
                'start_date'             => '2025-06-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-08-20 15:59:59',
                'date_range'             => '22 Juli – 20 Agustus 2025',
                'start_date'             => '2025-07-21 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-08-31 15:59:59',
                'date_range'             => '21 Agustus – 31 Agustus 2025',
                'start_date'             => '2025-08-20 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-10-02 15:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-10-01 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-10-19 15:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-10-18 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Babak Final',
                'end_date'               => '2025-10-31 15:59:59',
                'date_range'             => '31 Oktober 2025',
                'start_date'             => '2025-10-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Pengumuman Juara',
                'end_date'               => '2025-11-01 15:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-10-31 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Coming Soon',
                'end_date'               => '2025-06-30 15:59:59',
                'date_range'             => 'Comming Soon',
                'start_date'             => '2025-06-26 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-07-20 15:59:59',
                'date_range'             => '1-20 Juli 2025',
                'start_date'             => '2025-06-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-08-20 15:59:59',
                'date_range'             => '22 Juli-20 Agustus 2025',
                'start_date'             => '2025-07-21 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Pengumpulan Projek',
                'end_date'               => '2025-08-31 15:59:59',
                'date_range'             => '8 Juli-31 Agustus 2025',
                'start_date'             => '2025-07-07 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-08-31 15:59:59',
                'date_range'             => '21-31 Agustus 2025',
                'start_date'             => '2025-08-20 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-10-02 15:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-10-01 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-10-19 15:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-10-18 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Babak Final',
                'end_date'               => '2025-10-31 15:59:59',
                'date_range'             => '31 Oktober 2025',
                'start_date'             => '2025-10-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Pengumuman Juara',
                'end_date'               => '2025-11-01 15:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-10-31 16:00:01',
                'description'            => '',
            ],

            [
                'competition_content_id' => '11',
                'title'                  => 'Coming Soon',
                'end_date'               => '2025-06-30 15:59:59',
                'date_range'             => 'Comming Soon',
                'start_date'             => '2025-06-26 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-07-20 15:59:59',
                'date_range'             => '1-20 Juli 2025',
                'start_date'             => '2025-06-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-08-20 15:59:59',
                'date_range'             => '22 Juli-20 Agustus 2025',
                'start_date'             => '2025-07-21 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Pengumpulan Projek',
                'end_date'               => '2025-08-31 15:59:59',
                'date_range'             => '8 Juli-31 Agustus 2025',
                'start_date'             => '2025-07-07 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-08-31 15:59:59',
                'date_range'             => '21-31 Agustus 2025',
                'start_date'             => '2025-08-20 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-10-02 15:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-10-01 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-10-19 15:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-10-18 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Babak Final',
                'end_date'               => '2025-10-31 15:59:59',
                'date_range'             => '31 Oktober 2025',
                'start_date'             => '2025-10-30 16:00:01',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Pengumuman Juara',
                'end_date'               => '2025-11-01 15:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-10-31 16:00:01',
                'description'            => '',
            ],

        ];

        foreach ($competition_content_timelines as $competition_content_timeline) {
            CompetitionContentTimeline::create($competition_content_timeline);
        }
    }
}
