<?php
namespace Database\Seeders;

use App\Models\CompetitionContentTimeline;
use Illuminate\Database\Seeder;

class CompetitionContentTimelineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $competition_content_timelines = [
            [
                'competition_content_id' => '1',
                'title'                  => 'Pendaftaran Batch 1 dan Pengumpulan BMC',
                'end_date'               => '2025-06-04 23:59:59',
                'date_range'             => '1 - 20 Juli 2025',
                'start_date'             => '2025-05-31 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Pendaftaran Batch 2 dan Pengumpulan BMC',
                'end_date'               => '2025-06-08 23:59:59',
                'date_range'             => '21 Juli - 20 Agustus 2025',
                'start_date'             => '2025-06-05 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Perpanjangan Pendaftaran dan Pengumpulan BMC',
                'end_date'               => '2025-06-12 23:59:59',
                'date_range'             => '21 - 31 Agustus 2025',
                'start_date'             => '2025-06-09 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Pengumuman Finalis',
                'end_date'               => '2025-06-13 23:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-06-13 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Pengumpulan Proposal dan Video Iklan Singkat',
                'end_date'               => '2025-06-17 23:59:59',
                'date_range'             => '5 Oktober - 18 Oktober 2025',
                'start_date'             => '2025-06-14 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-06-21 23:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-06-18 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-06-22 23:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-06-22 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Expo Video Iklan Singkat',
                'end_date'               => '2025-06-23 23:59:59',
                'date_range'             => '22 Oktober - 29 Oktober 2025',
                'start_date'             => '2025-06-23 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Babak Final',
                'end_date'               => '2025-06-24 23:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-06-24 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '1',
                'title'                  => 'Pengumuman Juara',
                'end_date'               => '2025-06-25 23:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-06-25 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '2',
                'title'                  => 'Coming soon',
                'end_date'               => '2024-08-07 23:59:59',
                'date_range'             => 'Coming soon',
                'start_date'             => '2024-08-01 00:00:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-06-02 23:59:59',
                'date_range'             => '1 Juli – 20 Juli 2025',
                'start_date'             => '2025-05-31 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-06-04 23:59:59',
                'date_range'             => '22 Juli – 20 Agustus 2025',
                'start_date'             => '2025-06-03 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-06-07 23:59:59',
                'date_range'             => '21 Agustus – 31 Agustus 2025',
                'start_date'             => '2025-06-05 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-06-11 23:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-06-08 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-06-14 23:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-06-12 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Babak Final',
                'end_date'               => '2025-06-17 23:59:59',
                'date_range'             => '31 Oktober 2025',
                'start_date'             => '2025-06-15 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '3',
                'title'                  => 'Pengumuman Juara',
                'end_date'               => '2025-06-18 23:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-06-18 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '4',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-06-02 23:59:59',
                'date_range'             => '1 Juli – 20 Juli 2025',
                'start_date'             => '2025-05-31 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '4',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-06-05 23:59:59',
                'date_range'             => '22 Juli – 20 Agustus 2025',
                'start_date'             => '2025-06-03 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '4',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-06-08 23:59:59',
                'date_range'             => '21 Agustus – 31 Agustus 2025',
                'start_date'             => '2025-06-06 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '4',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-06-11 23:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-06-09 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '4',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-06-14 23:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-06-12 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '4',
                'title'                  => 'Babak Final',
                'end_date'               => '2025-06-17 23:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-06-15 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '4',
                'title'                  => 'Pengumuman Juara',
                'end_date'               => '2025-06-20 23:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-06-18 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-06-02 23:59:59',
                'date_range'             => '1-20 Juli 2025',
                'start_date'             => '2025-05-31 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-06-05 23:59:59',
                'date_range'             => '22 Juli-20 Agustus 2025',
                'start_date'             => '2025-06-03 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-06-08 23:59:59',
                'date_range'             => '21-31 Agustus 2025',
                'start_date'             => '2025-06-06 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Technical Meeting Penysihan',
                'end_date'               => '2025-06-12 23:59:59',
                'date_range'             => '5 September 2025',
                'start_date'             => '2025-06-09 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-06-15 23:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-06-13 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Technical Meeting Final',
                'end_date'               => '2025-06-18 23:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-06-16 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Babak Final	',
                'end_date'               => '2025-06-22 23:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-06-19 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '5',
                'title'                  => 'Pengumuman Juara',
                'end_date'               => '2025-06-24 23:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-06-23 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '6',
                'title'                  => 'Coming soon',
                'end_date'               => '2024-08-07 23:59:59',
                'date_range'             => 'Coming soon',
                'start_date'             => '2024-08-01 00:00:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-06-02 23:59:59',
                'date_range'             => '1-20 Juli 2025',
                'start_date'             => '2025-05-31 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-06-05 23:59:59',
                'date_range'             => '22 Juli-20 Agustus 2025',
                'start_date'             => '2025-06-03 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-06-08 23:59:59',
                'date_range'             => '21-31 Agustus 2025',
                'start_date'             => '2025-06-06 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-06-11 23:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-06-09 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Babak Penyisihan',
                'end_date'               => '2025-06-14 23:59:59',
                'date_range'             => '31 Oktober 2025',
                'start_date'             => '2025-06-12 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Babak Semifinal',
                'end_date'               => '2025-06-16 23:59:59',
                'date_range'             => '31 Oktober-1 November 2025',
                'start_date'             => '2025-06-15 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Babak Final',
                'end_date'               => '2025-06-18 23:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-06-17 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '7',
                'title'                  => 'Pengumuman Juara',
                'end_date'               => '2025-06-21 23:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-06-19 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-06-02 23:59:59',
                'date_range'             => '1 Juli - 20 Juli 2025',
                'start_date'             => '2025-05-31 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-06-05 23:59:59',
                'date_range'             => '22 Juli – 20 Agustus 2025',
                'start_date'             => '2025-06-03 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-06-08 23:59:59',
                'date_range'             => '21 Agustus – 31 Agustus 2025',
                'start_date'             => '2025-06-06 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-06-12 23:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-06-09 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-06-15 23:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-06-13 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Babak Final',
                'end_date'               => '2025-06-18 23:59:59',
                'date_range'             => '1 November 2025 ',
                'start_date'             => '2025-06-16 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '8',
                'title'                  => 'Pengumuman Juara',
                'end_date'               => '2025-06-20 23:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-06-19 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-06-02 23:59:59',
                'date_range'             => '1 Juli - 20 Juli 2025',
                'start_date'             => '2025-05-31 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-06-05 23:59:59',
                'date_range'             => '22 Juli – 20 Agustus 2025',
                'start_date'             => '2025-06-03 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-06-08 23:59:59',
                'date_range'             => '21 Agustus – 31 Agustus 2025',
                'start_date'             => '2025-06-06 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-06-11 23:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-06-09 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-06-14 23:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-06-12 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Babak Final',
                'end_date'               => '2025-06-16 23:59:59',
                'date_range'             => '31 Oktober 2025',
                'start_date'             => '2025-06-15 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '9',
                'title'                  => 'Pengumuman Juara',
                'end_date'               => '2025-06-18 23:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-06-17 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-06-02 23:59:59',
                'date_range'             => '1-20 Juli 2025',
                'start_date'             => '2025-05-31 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-06-05 23:59:59',
                'date_range'             => '22 Juli-20 Agustus 2025',
                'start_date'             => '2025-06-03 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Pengumpulan Projek',
                'end_date'               => '2025-06-07 23:59:59',
                'date_range'             => '8 Juli-31 Agustus 2025',
                'start_date'             => '2025-06-06 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-06-10 23:59:59',
                'date_range'             => '21-31 Agustus 2025',
                'start_date'             => '2025-06-08 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-06-12 23:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-06-11 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-06-14 23:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-06-12 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Babak Final',
                'end_date'               => '2025-06-16 23:59:59',
                'date_range'             => '31 Oktober 2025',
                'start_date'             => '2025-06-15 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '10',
                'title'                  => 'Pengumuman Juara',
                'end_date'               => '2025-06-19 23:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-06-17 00:01:00',
                'description'            => '',
            ],

            [
                'competition_content_id' => '11',
                'title'                  => 'Pendaftaran Batch 1',
                'end_date'               => '2025-06-02 23:59:59',
                'date_range'             => '1-20 Juli 2025',
                'start_date'             => '2025-05-31 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Pendaftaran Batch 2',
                'end_date'               => '2025-06-05 23:59:59',
                'date_range'             => '22 Juli-20 Agustus 2025',
                'start_date'             => '2025-06-03 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Pengumpulan Projek',
                'end_date'               => '2025-06-07 23:59:59',
                'date_range'             => '8 Juli-31 Agustus 2025',
                'start_date'             => '2025-06-06 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Perpanjangan Pendaftaran',
                'end_date'               => '2025-06-10 23:59:59',
                'date_range'             => '21-31 Agustus 2025',
                'start_date'             => '2025-06-08 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Pengumuman Top 10 Finalis',
                'end_date'               => '2025-06-12 23:59:59',
                'date_range'             => '2 Oktober 2025',
                'start_date'             => '2025-06-11 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Technical Meeting',
                'end_date'               => '2025-06-14 23:59:59',
                'date_range'             => '19 Oktober 2025',
                'start_date'             => '2025-06-12 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Babak Final',
                'end_date'               => '2025-06-16 23:59:59',
                'date_range'             => '31 Oktober 2025',
                'start_date'             => '2025-06-15 00:01:00',
                'description'            => '',
            ],
            [
                'competition_content_id' => '11',
                'title'                  => 'Pengumuman Juara',
                'end_date'               => '2025-06-19 23:59:59',
                'date_range'             => '1 November 2025',
                'start_date'             => '2025-06-17 00:01:00',
                'description'            => '',
            ],

        ];

        foreach ($competition_content_timelines as $competition_content_timeline) {
            CompetitionContentTimeline::create($competition_content_timeline);
        }
    }
}
